// Liste officielle CTM Maroc fournie par le client
// (booking.ctm.ma), completee par les villes demandees par le client final.
// Cette liste est volontairement
// canonique: une ancienne valeur stockee en base ne doit plus ajouter
// d'anciennes villes au dropdown.
export const VILLES_MAROC_DEFAUT = [
  "Agadir",
  "Agdez",
  "Agouim",
  "Ahfir",
  "Ain Dfali",
  "Ait Aissa",
  "Ait Melloul",
  "Ait Ouafqa",
  "Ait Ourir",
  "Akhfenir",
  "Aknoul",
  "Al Hoceima",
  "Aoufouss",
  "Azrou",
  "Bab Berred",
  "Bab Taza",
  "Bejaad",
  "Benslimane",
  "Ben Hadifa",
  "Beni Mathar",
  "Beni Mellal",
  "Beni yakhlef",
  "Berkane",
  "Bouarfa",
  "Boufakrane",
  "Bouizakarne",
  "Boujdour",
  "Boumalne Dadès",
  "Bouznika",
  "Casablanca",
  "Centre 44 ouled dlim",
  "Chefchaouen",
  "Cherafate",
  "Dakhla",
  "Dar bouazza",
  "Dardara",
  "Driouch",
  "Echemmaia",
  "El Jadida",
  "El hajeb",
  "Erfoud",
  "Errachidia",
  "Errahma",
  "Essaouira",
  "Fes",
  "Figuig",
  "Goulmima",
  "Guelmim",
  "Guenfouda",
  "Guerguerat",
  "Idaousmlal",
  "Ifrane",
  "Imzouren",
  "Inzegane",
  "Jbel Al-Aroui",
  "Jorf el malha",
  "Kasbat Tadla",
  "Kassita",
  "Kelaa Magouna",
  "Kelaa Sraghna",
  "Khemisset",
  "Khenifra",
  "Khouribga",
  "Ksar El Kébir",
  "Ktama Issaguen",
  "Laayoune",
  "Larache",
  "M'Hamid El Ghizlane",
  "Marrakech",
  "Mechra Bel Ksiri",
  "Meknes",
  "Midar",
  "Midelt",
  "Mirleft",
  "Mrirt",
  "Nador",
  "Nkob",
  "Oualidia",
  "Ouarzazate",
  "Ouazzane",
  "Oued Laabid",
  "Oued Zem",
  "Oujda",
  "Ouled Teima",
  "Rabat",
  "Rissani",
  "Safi",
  "Saidia",
  "Sale",
  "Salé",
  "Sebt Gzoula",
  "Sidi Bennour",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi rahal",
  "Sidi Smail",
  "Skoura",
  "Smara",
  "Souk Larbaa",
  "Tafraout",
  "Tagounite",
  "Taliouine",
  "Tamanar",
  "Tamaris",
  "Tamansourt",
  "Tamegroute",
  "Tamelelt",
  "Temara",
  "Tamorot",
  "Tan Tan",
  "Tanger",
  "Taounate",
  "Tarfaya",
  "Targuist",
  "Taroudant",
  "Taza",
  "Tazarine",
  "Taznakht",
  "Tendrara",
  "Tetouan",
  "Tighmi",
  "Tighssaline",
  "Tinghir",
  "Tinjdad",
  "Tinzouline",
  "Tiznit",
  "Zagora",
  "Zaida",
  "Zaouit Echeikh",
] as const;

export async function listerVillesMaroc(): Promise<string[]> {
  return [...VILLES_MAROC_DEFAUT];
}
