import { prisma } from "@/lib/db";

// Liste de référence des villes et localités du Maroc (grandes villes,
// chefs-lieux de province et petites communes urbaines/rurales notables),
// couvrant les 12 régions. Ordre alphabétique pour la sélection.
// L'admin peut réordonner/compléter via /admin/parametres (clé villes_maroc).
export const VILLES_MAROC_DEFAUT = [
  "Afourer",
  "Afra",
  "Agadir",
  "Agdz",
  "Aghbala",
  "Aghbalou",
  "Agourai",
  "Aguelmous",
  "Ahfir",
  "Ain Aicha",
  "Ain Beni Mathar",
  "Ain Cheggag",
  "Ain El Aouda",
  "Ain Erreggada",
  "Ain Harrouda",
  "Ain Leuh",
  "Ain Taoujdate",
  "Ain Zohra",
  "Ait Amira",
  "Ait Baha",
  "Ait Boubidmane",
  "Ait Daoud",
  "Ait Iaaza",
  "Ait Melloul",
  "Ait Ourir",
  "Ajdir",
  "Akhfennir",
  "Aklim",
  "Akka",
  "Aknoul",
  "Al Aroui",
  "Al Hoceima",
  "Alnif",
  "Amalou Ighriben",
  "Amizmiz",
  "Aoufous",
  "Aoulouz",
  "Aourir",
  "Arbaoua",
  "Arfoud",
  "Asilah",
  "Assa",
  "Assahrij",
  "Aousserd",
  "Azemmour",
  "Azilal",
  "Azrou",
  "Bab Berred",
  "Bab Taza",
  "Béni Mellal",
  "Béni Ansar",
  "Bejaad",
  "Ben Ahmed",
  "Ben Guerir",
  "Ben Taib",
  "Beni Bouayach",
  "Beni Boufrah",
  "Beni Yakhlef",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bhalil",
  "Biougra",
  "Bir Anzarane",
  "Bir Jdid",
  "Bni Bouayach",
  "Bni Chiker",
  "Bni Drar",
  "Bni Hadifa",
  "Bouabout",
  "Bouanane",
  "Bouarfa",
  "Boudinar",
  "Boudnib",
  "Boufakrane",
  "Boujdour",
  "Boujniba",
  "Boukhalef",
  "Boulemane",
  "Boumalne Dades",
  "Boumia",
  "Bouizakarne",
  "Bouknadel",
  "Bouskoura",
  "Bouznika",
  "Bradia",
  "Brikcha",
  "Bzou",
  "Casablanca",
  "Chefchaouen",
  "Chemaia",
  "Chichaoua",
  "Chtouka",
  "Dakhla",
  "Dar Bouazza",
  "Dar Chaoui",
  "Dar El Kebdani",
  "Debdou",
  "Demnate",
  "Deroua",
  "Dcheira El Jihadia",
  "Driouch",
  "El Aioun Sidi Mellouk",
  "El Argoub",
  "El Borouj",
  "El Gara",
  "El Hajeb",
  "El Jadida",
  "El Kbab",
  "El Kelaa des Sraghna",
  "El Ksiba",
  "El Marsa",
  "El Menzel",
  "El Ouatia",
  "Erfoud",
  "Errachidia",
  "Essaouira",
  "Farkhana",
  "Fès",
  "Figuig",
  "Fnideq",
  "Foum El Oued",
  "Foum Zguid",
  "Fam El Hisn",
  "Fquih Ben Salah",
  "Galaz",
  "Ghafsai",
  "Goulmima",
  "Gourrama",
  "Gueznaia",
  "Guelmim",
  "Guercif",
  "Guisser",
  "Had Bouhssoussen",
  "Had Kourt",
  "Had Soualem",
  "Harhoura",
  "Hattane",
  "Ifrane",
  "Ighoud",
  "Iggui",
  "Imilchil",
  "Imintanoute",
  "Imzouren",
  "Imouzzer Kandar",
  "Imouzzer Marmoucha",
  "Inezgane",
  "Jamaat Shaim",
  "Jebha",
  "Jerada",
  "Jorf",
  "Jorf El Melha",
  "Kariat Arekmane",
  "Kasba Tadla",
  "Kelaat Mgouna",
  "Kénitra",
  "Kerrouchen",
  "Kettara",
  "Khemis Zemamra",
  "Khemisset",
  "Khenichet",
  "Khénifra",
  "Khouribga",
  "Ksar El Kebir",
  "Ksar Sghir",
  "Laâyoune",
  "Larache",
  "Lqliaa",
  "Loudaya",
  "Loulad",
  "Martil",
  "Marrakech",
  "Massa",
  "Matmata",
  "Mdiq",
  "Mediouna",
  "Mehdia",
  "Meknès",
  "Mhamid",
  "Midar",
  "Midelt",
  "Missour",
  "Mohammedia",
  "Mokrisset",
  "Moulay Abdallah",
  "Moulay Bousselham",
  "Moulay Bouazza",
  "Moulay Brahim",
  "Moulay Yacoub",
  "Mrirt",
  "Nador",
  "Naima",
  "N'Kob",
  "Nouaceur",
  "Ouaouizeght",
  "Ouarzazate",
  "Ouazzane",
  "Oued Amlil",
  "Oued Laou",
  "Oued Zem",
  "Ouislane",
  "Oujda",
  "Oulad Berhil",
  "Oulad Frej",
  "Oulad Teima",
  "Oulmes",
  "Oulad Abbou",
  "Ounagha",
  "Outat El Haj",
  "Rabat",
  "Ras El Ain",
  "Ras El Ma",
  "Reggada",
  "Ribate El Kheir",
  "Rich",
  "Rissani",
  "Rommani",
  "Sabaa Aiyoun",
  "Safi",
  "Saidia",
  "Salé",
  "Sebt Gzoula",
  "Sefrou",
  "Selouane",
  "Settat",
  "Sidi Allal El Bahraoui",
  "Sidi Allal Tazi",
  "Sidi Bennour",
  "Sidi Bou Othmane",
  "Sidi Bouzid",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Rahal",
  "Sidi Slimane",
  "Sidi Smail",
  "Sidi Taibi",
  "Sidi Yahya El Gharb",
  "Skhirat",
  "Skhour Rehamna",
  "Skoura",
  "Smimou",
  "Souk El Arbaa",
  "Souk Sebt Oulad Nemma",
  "Tabounte",
  "Tafraout",
  "Taghazout",
  "Taghjijt",
  "Tahannaout",
  "Tahla",
  "Talmest",
  "Talsint",
  "Tamansourt",
  "Tamanar",
  "Tamegroute",
  "Tamesna",
  "Tamorot",
  "Tamri",
  "Tan-Tan",
  "Tanger",
  "Taourirt",
  "Taounate",
  "Tarfaya",
  "Taroudant",
  "Tata",
  "Taza",
  "Taznakht",
  "Tazarine",
  "Témara",
  "Temsia",
  "Tendrara",
  "Tétouan",
  "Tiddas",
  "Tiflet",
  "Tighassaline",
  "Tinejdad",
  "Tinghir",
  "Tissa",
  "Tit Mellil",
  "Tiznit",
  "Tnine Ourika",
  "Toulal",
  "Touima",
  "Youssoufia",
  "Zag",
  "Zagora",
  "Zaio",
  "Zaouiat Cheikh",
  "Zeghanghane",
  "Zemamra",
  "Zinat",
  "Zoumi",
];

function parserListeVilles(valeur?: string | null): string[] {
  if (!valeur) {
    return VILLES_MAROC_DEFAUT;
  }

  try {
    const parsed = JSON.parse(valeur);
    if (!Array.isArray(parsed)) {
      return VILLES_MAROC_DEFAUT;
    }

    const villes = parsed
      .filter((ville): ville is string => typeof ville === "string")
      .map((ville) => ville.trim())
      .filter(Boolean);

    return villes.length > 0 ? villes : VILLES_MAROC_DEFAUT;
  } catch {
    return VILLES_MAROC_DEFAUT;
  }
}

export async function listerVillesMaroc(): Promise<string[]> {
  const parametre = await prisma.parametreSysteme.findUnique({
    where: { cle: "villes_maroc" },
    select: { valeur: true },
  });

  return parserListeVilles(parametre?.valeur);
}
