import { prisma } from "@/lib/db";

// Liste de référence des villes et localités du Maroc (grandes villes,
// chefs-lieux de province et petites communes urbaines/rurales notables),
// couvrant les 12 régions. Ordre alphabétique pour la sélection.
// L'admin peut réordonner/compléter via /admin/parametres (clé villes_maroc).
const VILLES_MAROC_BASE = [
  "Afourer",
  "Afra",
  "Agadir",
  "Agdz",
  "Aghbala",
  "Aghbalou",
  "Agourai",
  "Aguelmous",
  "Ahfir",
  "Ain Aicha",
  "Ain Beni Mathar",
  "Ain Cheggag",
  "Ain El Aouda",
  "Ain Erreggada",
  "Ain Harrouda",
  "Ain Leuh",
  "Ain Taoujdate",
  "Ain Zohra",
  "Ait Amira",
  "Ait Baha",
  "Ait Boubidmane",
  "Ait Daoud",
  "Ait Iaaza",
  "Ait Melloul",
  "Ait Ourir",
  "Ajdir",
  "Akhfennir",
  "Aklim",
  "Akka",
  "Aknoul",
  "Al Aroui",
  "Al Hoceima",
  "Alnif",
  "Amalou Ighriben",
  "Amizmiz",
  "Aoufous",
  "Aoulouz",
  "Aourir",
  "Arbaoua",
  "Arfoud",
  "Asilah",
  "Assa",
  "Assahrij",
  "Aousserd",
  "Azemmour",
  "Azilal",
  "Azrou",
  "Bab Berred",
  "Bab Taza",
  "Béni Mellal",
  "Béni Ansar",
  "Bejaad",
  "Ben Ahmed",
  "Ben Guerir",
  "Ben Taib",
  "Beni Bouayach",
  "Beni Boufrah",
  "Beni Yakhlef",
  "Benslimane",
  "Berkane",
  "Berrechid",
  "Bhalil",
  "Biougra",
  "Bir Anzarane",
  "Bir Jdid",
  "Bni Bouayach",
  "Bni Chiker",
  "Bni Drar",
  "Bni Hadifa",
  "Bouabout",
  "Bouanane",
  "Bouarfa",
  "Boudinar",
  "Boudnib",
  "Boufakrane",
  "Boujdour",
  "Boujniba",
  "Boukhalef",
  "Boulemane",
  "Boumalne Dades",
  "Boumia",
  "Bouizakarne",
  "Bouknadel",
  "Bouskoura",
  "Bouznika",
  "Bradia",
  "Brikcha",
  "Bzou",
  "Casablanca",
  "Chefchaouen",
  "Chemaia",
  "Chichaoua",
  "Chtouka",
  "Dakhla",
  "Dar Bouazza",
  "Dar Chaoui",
  "Dar El Kebdani",
  "Debdou",
  "Demnate",
  "Deroua",
  "Dcheira El Jihadia",
  "Driouch",
  "El Aioun Sidi Mellouk",
  "El Argoub",
  "El Borouj",
  "El Gara",
  "El Hajeb",
  "El Jadida",
  "El Kbab",
  "El Kelaa des Sraghna",
  "El Ksiba",
  "El Marsa",
  "El Menzel",
  "El Ouatia",
  "Erfoud",
  "Errachidia",
  "Essaouira",
  "Farkhana",
  "Fès",
  "Figuig",
  "Fnideq",
  "Foum El Oued",
  "Foum Zguid",
  "Fam El Hisn",
  "Fquih Ben Salah",
  "Galaz",
  "Ghafsai",
  "Goulmima",
  "Gourrama",
  "Gueznaia",
  "Guelmim",
  "Guercif",
  "Guisser",
  "Had Bouhssoussen",
  "Had Kourt",
  "Had Soualem",
  "Harhoura",
  "Hattane",
  "Ifrane",
  "Ighoud",
  "Iggui",
  "Imilchil",
  "Imintanoute",
  "Imzouren",
  "Imouzzer Kandar",
  "Imouzzer Marmoucha",
  "Inezgane",
  "Jamaat Shaim",
  "Jebha",
  "Jerada",
  "Jorf",
  "Jorf El Melha",
  "Kariat Arekmane",
  "Kasba Tadla",
  "Kelaat Mgouna",
  "Kénitra",
  "Kerrouchen",
  "Kettara",
  "Khemis Zemamra",
  "Khemisset",
  "Khenichet",
  "Khénifra",
  "Khouribga",
  "Ksar El Kebir",
  "Ksar Sghir",
  "Laâyoune",
  "Larache",
  "Lqliaa",
  "Loudaya",
  "Loulad",
  "Martil",
  "Marrakech",
  "Massa",
  "Matmata",
  "Mdiq",
  "Mediouna",
  "Mehdia",
  "Meknès",
  "Mhamid",
  "Midar",
  "Midelt",
  "Missour",
  "Mohammedia",
  "Mokrisset",
  "Moulay Abdallah",
  "Moulay Bousselham",
  "Moulay Bouazza",
  "Moulay Brahim",
  "Moulay Yacoub",
  "Mrirt",
  "Nador",
  "Naima",
  "N'Kob",
  "Nouaceur",
  "Ouaouizeght",
  "Ouarzazate",
  "Ouazzane",
  "Oued Amlil",
  "Oued Laou",
  "Oued Zem",
  "Ouislane",
  "Oujda",
  "Oulad Berhil",
  "Oulad Frej",
  "Oulad Teima",
  "Oulmes",
  "Oulad Abbou",
  "Ounagha",
  "Outat El Haj",
  "Rabat",
  "Ras El Ain",
  "Ras El Ma",
  "Reggada",
  "Ribate El Kheir",
  "Rich",
  "Rissani",
  "Rommani",
  "Sabaa Aiyoun",
  "Safi",
  "Saidia",
  "Salé",
  "Sebt Gzoula",
  "Sefrou",
  "Selouane",
  "Settat",
  "Sidi Allal El Bahraoui",
  "Sidi Allal Tazi",
  "Sidi Bennour",
  "Sidi Bou Othmane",
  "Sidi Bouzid",
  "Sidi Ifni",
  "Sidi Kacem",
  "Sidi Rahal",
  "Sidi Slimane",
  "Sidi Smail",
  "Sidi Taibi",
  "Sidi Yahya El Gharb",
  "Skhirat",
  "Skhour Rehamna",
  "Skoura",
  "Smimou",
  "Souk El Arbaa",
  "Souk Sebt Oulad Nemma",
  "Tabounte",
  "Tafraout",
  "Taghazout",
  "Taghjijt",
  "Tahannaout",
  "Tahla",
  "Talmest",
  "Talsint",
  "Tamansourt",
  "Tamanar",
  "Tamegroute",
  "Tamesna",
  "Tamorot",
  "Tamri",
  "Tan-Tan",
  "Tanger",
  "Taourirt",
  "Taounate",
  "Tarfaya",
  "Taroudant",
  "Tata",
  "Taza",
  "Taznakht",
  "Tazarine",
  "Témara",
  "Temsia",
  "Tendrara",
  "Tétouan",
  "Tiddas",
  "Tiflet",
  "Tighassaline",
  "Tinejdad",
  "Tinghir",
  "Tissa",
  "Tit Mellil",
  "Tiznit",
  "Tnine Ourika",
  "Toulal",
  "Touima",
  "Youssoufia",
  "Zag",
  "Zagora",
  "Zaio",
  "Zaouiat Cheikh",
  "Zeghanghane",
  "Zemamra",
  "Zinat",
  "Zoumi",
];

// Complement issu du dump public MIT alaouy/sql-moroccan-cities (villes + regions).
// La base ci-dessus reste conservee, puis ce complement est dedoublonne.
const VILLES_MAROC_COMPLEMENT = [
  "Afourar",
  "Agni Izimmer",
  "A\u00efn Bni Mathar",
  "A\u00efn Dorij",
  "A\u00efn Jemaa",
  "A\u00efn Karma",
  "A\u00eft Attab",
  "A\u00eft Hichem",
  "A\u00eft Ishaq",
  "A\u00eft Majden",
  "A\u00eft Yalla",
  "Akchour",
  "Anzi",
  "Arazane",
  "Assilah",
  "Awsard",
  "Ben Sergao",
  "Ben Ta\u00efeb",
  "Ben Yakhlef",
  "Beni Ayat",
  "Bin elouidane",
  "Bni Ansar",
  "Bni Tadjite",
  "Bouguedra",
  "Bouhdila",
  "Boulanouare",
  "Dar Bni Karrich",
  "Dar Gueddari",
  "Dar Oulad Zidouh",
  "Douar Kannine",
  "Dra'a",
  "Drargua",
  "Echemmaia",
  "El Guerdane",
  "El Hanchane",
  "Er-Rich",
  "Es-Semara",
  "Foum Jamaa",
  "Fra\u00efta",
  "Gardmit",
  "Ghmate",
  "Guigou",
  "Haj Kaddour",
  "Harte Lyamine",
  "Hrara",
  "Ida Ougnidif",
  "Ifri",
  "Igdamen",
  "Ighil n'Oumgoun",
  "Ighounane",
  "Ihddaden",
  "Imassine",
  "Inahnahen",
  "Irherm",
  "Issaguen (Ketama)",
  "Itzer",
  "Ja\u00e2dar",
  "Jorf Lasfar",
  "Karia",
  "Karia (El Jadida)",
  "Karia Ba Mohamed",
  "Kassita",
  "Kattara",
  "Kehf Nsour",
  "Kerouna",
  "Kh\u00e9mis Sahel",
  "Laaounate",
  "La\u00e2tamna",
  "L\u00e2attaouia",
  "Lakhsas",
  "Lakhsass",
  "Lalla Mimouna",
  "Lalla Takerkoust",
  "M'haya",
  "M'semrir",
  "Madagh",
  "Massa (Maroc)",
  "Mechra Bel Ksiri",
  "Megousse",
  "Mohammadia",
  "Moqrisset",
  "Moulay Ali Cherif",
  "Moulay Idriss Zerhoun",
  "Moulay Ya\u00e2coub",
  "Moussaoua",
  "MyAliCherif",
  "Mzouda",
  "N'Zalat Bni Amar",
  "Oualidia",
  "Ouaoumana",
  "Oued Heimer",
  "Oued Ifrane",
  "Oued Rmel",
  "Oued-Eddahab",
  "Oulad Amrane",
  "Oulad Ayad",
  "Oulad Ghadbane",
  "Oulad H'Riz Sahel",
  "Oulad M'Barek",
  "Oulad M'rah",
  "Oulad Sa\u00efd",
  "Oulad Sidi Ben Daoud",
  "Oulad Yaich",
  "Oulad Zbair",
  "Ouled Tayeb",
  "Point Cires",
  "Sarghine",
  "Sebt El Ma\u00e2rif",
  "Sebt Jahjouh",
  "Sid L'Mokhtar",
  "Sid Zouin",
  "Sidi Abdallah Ghiat",
  "Sidi Addi",
  "Sidi Ahmed",
  "Sidi Ali Ban Hamdouche",
  "Sidi Boubker",
  "Sidi Bouknadel",
  "Sidi Jaber",
  "Sidi Lyamani",
  "Sidi Mohamed ben Abdallah el-Raisuni",
  "Sidi Rahhal",
  "Sidi Rahhal Chata\u00ef",
  "Sidi Slimane Echcharaa",
  "Skhinate",
  "Skhirate",
  "Soualem",
  "Stehat",
  "Tafajight",
  "Tafetachte",
  "Taghzout",
  "Tagzen",
  "Ta\u00efnaste",
  "Tala Tazegwaght",
  "Taliouine",
  "Tamallalt",
  "Tamassint",
  "Tameslouht",
  "Tamraght",
  "Tanalt",
  "Tanoumrite Nkob Zagora",
  "Taourirt ait zaghar",
  "Targuist",
  "Taroudannt",
  "Thar Es-Souk",
  "Tichoute",
  "Tifnit",
  "Tighza",
  "Timahdite",
  "Tisgdal",
  "Tizguite",
  "Tizi Ouasli",
  "Tiztoutine",
  "Touarga",
  "Touissit",
  "Toundoute",
  "Tounfite",
  "Za\u00efda",
  "Zaouia d'Ifrane",
  "Zeubelemok",
];

export const VILLES_MAROC_DEFAUT = Array.from(
  new Set([...VILLES_MAROC_BASE, ...VILLES_MAROC_COMPLEMENT]),
).sort((a, b) => a.localeCompare(b, "fr", { sensitivity: "base" }));

function parserListeVilles(valeur?: string | null): string[] {
  if (!valeur) {
    return VILLES_MAROC_DEFAUT;
  }

  try {
    const parsed = JSON.parse(valeur);
    if (!Array.isArray(parsed)) {
      return VILLES_MAROC_DEFAUT;
    }

    const villes = parsed
      .filter((ville): ville is string => typeof ville === "string")
      .map((ville) => ville.trim())
      .filter(Boolean);

    return villes.length > 0 ? villes : VILLES_MAROC_DEFAUT;
  } catch {
    return VILLES_MAROC_DEFAUT;
  }
}

export async function listerVillesMaroc(): Promise<string[]> {
  const parametre = await prisma.parametreSysteme.findUnique({
    where: { cle: "villes_maroc" },
    select: { valeur: true },
  });

  return parserListeVilles(parametre?.valeur);
}
